"use client";

import { Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { decodeShareData } from "@/lib/share";
import { computeGpa, totalCredits } from "@/lib/gpa";
import { generateTranscriptPdf } from "@/lib/pdf";

function SharedTranscript() {
  const searchParams = useSearchParams();
  const encoded = searchParams.get("d");
  const bundle = encoded ? decodeShareData(encoded) : null;

  if (!bundle) {
    return <p className="text-muted text-sm">This share link is invalid or has expired.</p>;
  }

  const { student, courses } = bundle;
  const gpa = computeGpa(courses);
  const credits = totalCredits(courses);

  return (
    <div className="flex flex-col gap-8">
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-bold mb-1">Shared Transcript</h1>
          <p className="text-muted text-sm">Read-only view generated by FreeLoom.</p>
        </div>
        <button onClick={() => generateTranscriptPdf(student, courses)} className="btn-primary">
          Download PDF
        </button>
      </div>

      <div className="rounded-lg border border-border bg-surface p-6">
        <div className="text-xl font-semibold mb-1">{student.name || "Unnamed Student"}</div>
        <div className="text-muted text-sm mb-6">{student.gradeLevel || "Grade level not set"}</div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-muted border-b border-border">
                <th className="py-2 pr-4 font-medium">Course Title</th>
                <th className="py-2 pr-4 font-medium">Subject Area</th>
                <th className="py-2 pr-4 font-medium">Credits</th>
                <th className="py-2 font-medium">Grade</th>
              </tr>
            </thead>
            <tbody>
              {courses.map((course) => (
                <tr key={course.id} className="border-b border-border/60">
                  <td className="py-2.5 pr-4">{course.title}</td>
                  <td className="py-2.5 pr-4 text-muted">{course.subjectArea}</td>
                  <td className="py-2.5 pr-4">{course.creditHours.toFixed(2)}</td>
                  <td className="py-2.5">{course.grade}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="flex gap-8 mt-6 pt-4 border-t border-border text-sm">
          <div>
            <span className="text-muted">Cumulative Credit Hours: </span>
            <span className="font-semibold">{credits.toFixed(2)}</span>
          </div>
          <div>
            <span className="text-muted">Cumulative GPA: </span>
            <span className="font-semibold text-gold">{gpa.toFixed(2)}</span>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function SharePage() {
  return (
    <Suspense fallback={null}>
      <SharedTranscript />
    </Suspense>
  );
}
