import Link from "next/link";
import LogoMark from "@/components/LogoMark";

const LAST_UPDATED = "July 22, 2026";

/** Standalone page (like /login, /privacy) -- reachable both signed out and
 * signed in, so it deliberately doesn't sit inside the (app) route group's
 * nav-rail chrome. */
export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl w-full flex flex-col gap-8 py-16 px-4 sm:px-6">
      <div className="text-center">
        <Link href="/" className="inline-flex mb-4">
          <LogoMark size={48} />
        </Link>
        <h1 className="text-2xl font-bold font-serif">Terms of Service</h1>
        <p className="text-muted text-sm mt-2">Last updated {LAST_UPDATED}.</p>
      </div>

      <div className="rounded-lg border border-navy-line bg-navy-soft px-4 py-3 text-sm text-muted">
        This page describes the actual terms FreeLoom operates under today. Questions about anything on it are
        welcome any time -- see the Questions section below.
      </div>

      <section className="flex flex-col gap-3">
        <h2 className="font-serif text-lg font-bold">Who can use FreeLoom</h2>
        <p className="text-sm text-muted">
          You must be at least 18 years old and the parent or legal guardian of any student whose information you
          add, to create a FreeLoom account. Student profiles are for your own children/students -- FreeLoom
          doesn&apos;t collect information directly from a child, and children don&apos;t have their own login.
        </p>
      </section>

      <section className="flex flex-col gap-3">
        <h2 className="font-serif text-lg font-bold">What FreeLoom is</h2>
        <p className="text-sm text-muted">
          FreeLoom is a record-keeping tool: you describe what your student did, and it drafts a structured class
          entry with its reasoning shown alongside it. You review, edit, or write every entry yourself -- FreeLoom
          never publishes anything to a transcript or portfolio without your review. Transcripts generated by
          FreeLoom are a formatting and organizing tool; you&apos;re responsible for whether they meet the specific
          requirements of any evaluator, program, or authority you submit them to.
        </p>
      </section>

      <section className="flex flex-col gap-3">
        <h2 className="font-serif text-lg font-bold">Your account</h2>
        <ul className="list-disc list-inside text-sm text-muted flex flex-col gap-1.5">
          <li>You&apos;re responsible for keeping your login credentials secure.</li>
          <li>One account covers your whole family -- add each student as their own profile.</li>
          <li>You own the content you enter. We don&apos;t claim any rights to your students&apos; records beyond
            what&apos;s needed to operate the service for you (storing it, generating transcripts/portfolios from
            it, and the limited processing described in our{" "}
            <Link href="/privacy" className="text-gold hover:underline">
              Privacy &amp; Cookie Policy
            </Link>
            ).
          </li>
        </ul>
      </section>

      <section className="flex flex-col gap-3">
        <h2 className="font-serif text-lg font-bold">Billing</h2>
        <ul className="list-disc list-inside text-sm text-muted flex flex-col gap-1.5">
          <li>Free, Pro, and Premium plans are billed as described on our pricing page, monthly, quarterly, or
            yearly.</li>
          <li><strong>Charges are final -- we don&apos;t offer refunds.</strong> You can cancel at any time, and
            you&apos;ll keep access through the end of the period you already paid for.</li>
          <li>Switching plans (upgrading, downgrading, or changing your billing interval) prorates the difference
            on your next invoice, shown to you before you confirm the change.</li>
          <li>If a payment fails, we give you a grace period to update your payment method before your plan
            reverts to Free; we&apos;ll email you and notify you in-app when that happens.</li>
          <li>Downgrading to a plan with a lower student limit doesn&apos;t delete any existing student profiles --
            profiles beyond your new limit are preserved but locked from new edits until your plan covers them
            again.</li>
        </ul>
      </section>

      <section className="flex flex-col gap-3">
        <h2 className="font-serif text-lg font-bold">Acceptable use</h2>
        <p className="text-sm text-muted">
          Use FreeLoom only for its intended purpose -- keeping real records for your own family. Don&apos;t use it
          to store information about someone else&apos;s children without authorization, attempt to access another
          account, or interfere with the service&apos;s normal operation.
        </p>
      </section>

      <section className="flex flex-col gap-3">
        <h2 className="font-serif text-lg font-bold">Ending your account</h2>
        <p className="text-sm text-muted">
          You can close your account any time in Settings &gt; Account, which deletes your data as described in our{" "}
          <Link href="/privacy" className="text-gold hover:underline">
            Privacy &amp; Cookie Policy
          </Link>
          . We may suspend or terminate an account that violates the acceptable-use terms above, or that we
          reasonably believe was created fraudulently.
        </p>
      </section>

      <section className="flex flex-col gap-3">
        <h2 className="font-serif text-lg font-bold">No warranty, limited liability</h2>
        <p className="text-sm text-muted">
          FreeLoom is provided as-is. We work to keep it reliable and your data safe, but we don&apos;t guarantee
          the service will be uninterrupted or error-free, and we&apos;re not liable for indirect or consequential
          damages arising from your use of it, to the extent the law allows us to limit that.
        </p>
      </section>

      <section className="flex flex-col gap-3">
        <h2 className="font-serif text-lg font-bold">Changes to these terms</h2>
        <p className="text-sm text-muted">
          If these terms change in a way that meaningfully affects you, we&apos;ll notify you in-app or by email
          before it takes effect.
        </p>
      </section>

      <section className="flex flex-col gap-3">
        <h2 className="font-serif text-lg font-bold">Questions</h2>
        <p className="text-sm text-muted">
          The fastest way to reach us is through the Messages feature in your account, if you&apos;re signed in.
          Otherwise, email{" "}
          <a href="mailto:support@freeloom.io" className="text-gold hover:underline">
            support@freeloom.io
          </a>
          .
        </p>
      </section>
    </div>
  );
}
