import { createClient } from "@/lib/supabase/server";
import { computeGpa, groupByGradeLevel } from "@/lib/gpa";

type SharedTranscript = {
  transcript_id: string;
  generated_at: string;
  pdf_url: string | null;
  student: {
    name: string;
    grade_level: string | null;
    gender: string | null;
    birth_date: string | null;
    graduation_date: string | null;
    expected_graduation_year: number | null;
  };
  school: {
    school_name: string | null;
    parent_name: string | null;
    address: string | null;
    phone: string | null;
    email: string | null;
    logo_url: string | null;
    accent_color: string | null;
    layout_style: "formal" | "casual" | null;
  };
  courses: { course_title: string; subject_area: string; credit_hours: number; letter_grade: string | null; grade_level: string | null }[];
  total_credit_hours: number;
};

function formatDate(value: string | null): string {
  if (!value) return "—";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return value;
  return d.toLocaleDateString();
}

export default async function SharePage({ params }: { params: Promise<{ transcriptId: string }> }) {
  const { transcriptId } = await params;
  const supabase = await createClient();

  const { data, error } = await supabase.rpc("get_shared_transcript", { p_transcript_id: transcriptId });
  if (error) console.error("get_shared_transcript RPC failed", error);
  const shared = data as SharedTranscript | null;

  // A separate, dedicated RPC rather than folding this into
  // get_shared_transcript's own query -- revoking is a newer, additive
  // concept layered on top of an existing function whose exact original
  // SQL isn't tracked in this repo, so this checks it independently
  // instead of risking a subtle change to that function's behavior.
  const { data: revoked } = await supabase.rpc("is_transcript_share_revoked", { p_transcript_id: transcriptId });

  if (!shared || revoked) {
    return <p className="text-muted text-sm">This share link is invalid or has expired.</p>;
  }

  const accent = shared.school.accent_color || undefined;
  const grouped = groupByGradeLevel(shared.courses);
  const cumulative = computeGpa(shared.courses);
  const gradDateLabel = shared.student.graduation_date
    ? formatDate(shared.student.graduation_date)
    : shared.student.expected_graduation_year
    ? `Expected ${shared.student.expected_graduation_year}`
    : "—";

  return (
    <div className="flex flex-col gap-8">
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div className="flex items-center gap-3">
          {shared.school.logo_url && (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={shared.school.logo_url} alt="" className="h-10 w-10 rounded-full object-cover" />
          )}
          <div>
            <h1 className="text-2xl font-bold mb-1">
              {shared.school.layout_style === "casual" ? "Learning Record" : "Official High School Transcript"}
            </h1>
            <p className="text-muted text-sm">Read-only view generated by FreeLoom. Graduation date: {gradDateLabel}</p>
          </div>
        </div>
        <a href={`/api/transcript-pdf/${transcriptId}`} className="btn-primary">
          Download PDF
        </a>
      </div>

      <div className="rounded-lg border border-border bg-surface shadow-sm p-6 flex flex-col gap-8">
        <div className="grid gap-6 sm:grid-cols-2">
          <div>
            <div className="text-xs font-semibold text-gold uppercase mb-1" style={{ color: accent }}>School of Record</div>
            <div className="text-sm">{shared.school.school_name || "Homeschool"}</div>
            {shared.school.parent_name && <div className="text-sm text-muted">{shared.school.parent_name}</div>}
            {shared.school.address && <div className="text-sm text-muted">{shared.school.address}</div>}
            {shared.school.phone && <div className="text-sm text-muted">{shared.school.phone}</div>}
            {shared.school.email && <div className="text-sm text-muted">{shared.school.email}</div>}
          </div>
          <div>
            <div className="text-xs font-semibold text-gold uppercase mb-1" style={{ color: accent }}>Student Information</div>
            <div className="text-sm">{shared.student.name || "Unnamed Student"}</div>
            {shared.student.gender && <div className="text-sm text-muted">Gender: {shared.student.gender}</div>}
            <div className="text-sm text-muted">Date of Birth: {formatDate(shared.student.birth_date)}</div>
          </div>
        </div>

        {grouped.length === 0 ? (
          <p className="text-muted text-sm">No approved courses yet.</p>
        ) : (
          grouped.map((bucket) => {
            const blockGpa = computeGpa(bucket.courses);
            return (
              <div key={bucket.level}>
                <h2 className="font-semibold mb-2">
                  Course Study {bucket.level === "Other" ? "" : `— Grade ${bucket.level}`}
                </h2>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="text-left text-muted border-b border-border">
                        <th className="py-2 pr-4 font-medium">Course Title</th>
                        <th className="py-2 pr-4 font-medium">Subject Area</th>
                        <th className="py-2 pr-4 font-medium">Grade</th>
                        <th className="py-2 font-medium">Credits</th>
                      </tr>
                    </thead>
                    <tbody>
                      {bucket.courses.map((course, i) => (
                        <tr key={i} className="border-b border-border/60">
                          <td className="py-2.5 pr-4">{course.course_title}</td>
                          <td className="py-2.5 pr-4 text-muted">{course.subject_area}</td>
                          <td className="py-2.5 pr-4">{course.letter_grade || "—"}</td>
                          <td className="py-2.5">{course.credit_hours.toFixed(2)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                {blockGpa.gpa !== null && (
                  <div className="text-right text-sm font-semibold mt-2">GPA: {blockGpa.gpa.toFixed(2)}</div>
                )}
              </div>
            );
          })
        )}

        <div className="grid gap-4 sm:grid-cols-2 pt-4 border-t border-border text-sm">
          <div>
            <div className="text-muted">Total Credits</div>
            <div className="font-semibold text-gold" style={{ color: accent }}>{shared.total_credit_hours.toFixed(2)}</div>
          </div>
          <div>
            <div className="text-muted">Cumulative GPA</div>
            <div className="font-semibold text-gold" style={{ color: accent }}>{cumulative.gpa !== null ? cumulative.gpa.toFixed(2) : "—"}</div>
          </div>
        </div>
      </div>
    </div>
  );
}
