import { createClient } from "@/lib/supabase/server";

type SharedTranscript = {
  transcript_id: string;
  generated_at: string;
  pdf_url: string | null;
  student: { name: string; grade_level: string | null };
  courses: { course_title: string; subject_area: string; credit_hours: number }[];
  total_credit_hours: number;
};

export default async function SharePage({ params }: { params: Promise<{ transcriptId: string }> }) {
  const { transcriptId } = await params;
  const supabase = await createClient();

  const { data } = await supabase.rpc("get_shared_transcript", { p_transcript_id: transcriptId });
  const shared = data as SharedTranscript | null;

  if (!shared) {
    return <p className="text-muted text-sm">This share link is invalid or has expired.</p>;
  }

  return (
    <div className="flex flex-col gap-8">
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-bold mb-1">Shared Transcript</h1>
          <p className="text-muted text-sm">Read-only view generated by FreeLoom.</p>
        </div>
        <a href={`/api/transcript-pdf/${transcriptId}`} className="btn-primary">
          Download PDF
        </a>
      </div>

      <div className="rounded-lg border border-border bg-surface shadow-sm p-6">
        <div className="text-xl font-semibold mb-1">{shared.student.name || "Unnamed Student"}</div>
        <div className="text-muted text-sm mb-6">{shared.student.grade_level || "Grade level not set"}</div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-muted border-b border-border">
                <th className="py-2 pr-4 font-medium">Course Title</th>
                <th className="py-2 pr-4 font-medium">Subject Area</th>
                <th className="py-2 font-medium">Credits</th>
              </tr>
            </thead>
            <tbody>
              {shared.courses.map((course, i) => (
                <tr key={i} className="border-b border-border/60">
                  <td className="py-2.5 pr-4">{course.course_title}</td>
                  <td className="py-2.5 pr-4 text-muted">{course.subject_area}</td>
                  <td className="py-2.5">{course.credit_hours.toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="mt-6 pt-4 border-t border-border text-sm">
          <span className="text-muted">Cumulative Credit Hours: </span>
          <span className="font-semibold text-gold">{shared.total_credit_hours.toFixed(2)}</span>
        </div>
      </div>
    </div>
  );
}
